### ISSUE TITLE
JMS\Serializer\NormalizerInterface ERROR

### ISSUE THREAD

**Issue by elchappo** [eole-io/sandstone#1]
Hi, I get that error when running your example @ https://eole-io.github.io/sandstone/examples/multichannel-chat.html

`Fatal error: Uncaught TypeError: Argument 1 passed to Eole\Sandstone\Websocket\Topic::setNormalizer() must be an instance of JMS\Serializer\NormalizerInterface, instance of JMS\Serializer\Serializer given, called in /src/vendor/eole/sandstone/src/Websocket/Application.php`

**Comment by alcalyn** [comment]
Yep I've seen this error yestarday, this is because I upgraded to jms/serializer 1.4, and I don't have seen this error when running tests.
I'll work on a patch soon, but you can for now use Sandstone `1.1.x` instead of `1.2.x`

**Comment by alcalyn** [comment]
Fixed in `1.2.1`
