### ISSUE TITLE
Chat server example not working !

### ISSUE THREAD

**Issue by miranos** [eole-io/sandstone#9]
Hi,

I am trying from last day to figure out this problem, but without any solution.

I am talking about this example:
https://eole-io.github.io/sandstone-doc/examples/multichannel-chat

I's not updated so this will work with the new autobahn ... since the one presented on this example seem broken:
`<script src="http://autobahn.s3.amazonaws.com/js/autobahn.min.js"></script>`

Any working example please ?

Thank you

**Comment by alcalyn** [comment]
Hello, yes this file has been removed from amazon, you can use this one: https://github.com/eole-io/sandstone-doc-live/blob/master/src/autobahn.min.js

You have a working example here (see "Live exemples" section): https://eole-io.github.io/sandstone-doc

**Comment by alcalyn** [comment]
I usually download this file in my project as I can't find it in npm or cdn...

**Comment by miranos** [comment]
Thank you !

Is there any example on how to share sessions between apache and websocket please ?

Without using Symphony.

**Comment by alcalyn** [comment]
Yes, someone already needed this, so I created this example you can run with Docker: https://github.com/alcalyn/ratchet-session-pdo

It shares sessions by storing them in database, using `Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler`:

https://github.com/alcalyn/ratchet-session-pdo/blob/master/www/index.php#L9-L23

I'm not sure what you mean by "not using symfony" and why, but the `PdoSessionHandler` can be configured to choose the column names, table... and you can retrieve entries as you wish

**Comment by miranos** [comment]
Hi,

Big thank's for your quick answer !

Since i am developing a pure PHP application, i don't want to integrate any framework based project on it.

Is there a way to use it without DOCKER aswell ?

Thank you in advance and thank's for this awesome work !

Some other questions:
- Do you have some stats about how much resources used on the server ? How much connection can be simultaniously be connected on any specific VPS (For example CPU 2 x 3GHz, 5 Go RAM ) ?

**Comment by alcalyn** [comment]
> Since i am developing a pure PHP application, i don't want to integrate any framework based project on it.

I'm not sure which level of "pure php" application you want, but Sandstone is a microframework based on Silex which is a microframework (end of life however), and RatchetPHP and some Symfony components, that are independant PHP libraries. So you are free to start on a lower level, by using some of these libraries, or search for other libraries you can play with websocket (I seen https://github.com/voryx/Thruway which is more modern, but less documented I think).

And if you are using the edition but want something more minimalist, you can you Sandstone as is, it's like Silex, but with websockets topics. The [Full example](https://eole-io.github.io/sandstone-doc/examples/full.html) don't uses the edition.

> Is there a way to use it without DOCKER aswell ?

Docker is optional, indeed you can run a Sandstone application by installing packages directly on your computer. I assume you are using the Sandstone edition, so you can see "Normal installation" here: https://eole-io.github.io/sandstone-doc/edition/get-started

> Do you have some stats about how much resources used on the server ?

Unfortunately I don't have any serious benchmark. However I drafted something to compare PHP vs NodeJS websocket where I'm using Sandstone and socket.io: https://github.com/alcalyn/websocket-benchmark

**Comment by miranos** [comment]
When i was looking for a solution for websocket, i found about Thruway, but like you said, there no working example and zero documentation.

But yours, working well and well documented ... it's the best i found until now.

https://github.com/alcalyn/websocket-benchmark

This is a good news ! I was on debate with myself about what solution will be used for my application (NodeJS or PHP) ... i think i bet on the right one :)

Thank you again and sorry for your time answering my questions !
